version: "3.8"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - fs
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    secrets:
      - postgres_password

  app:
    image: ghcr.io/joseederangojr/fs:${GIT_COMMIT_HASH}
    environment:
      APP_URL: https://fs.joseederangojr.site
      APP_ENV: production
      JWT_EXP: 3
      HASH_ROUNDS: 10
      BODY_LIMIT: 100
      CORS_ORIGIN: https://fs.joseederangojr.site
      PORT: 3000
      DATABASE_URL_FILE: /run/secrets/database_url
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - fs
      - public
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    secrets:
      - database_url
      - jwt_secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fs-api.rule=Host(`fs.joseederangojr.site`) && PathPrefix(`/api`)"
      - "traefik.http.routers.fs-api.entrypoints=websecure"
      - "traefik.http.routers.fs-api.tls=true"
      - "traefik.http.services.fs-api.loadbalancer.server.port=3000"
      - "traefik.http.routers.fs-api.service=fs-api"
    depends_on:
      - postgres
      - migrate

  migrate:
    image: ghcr.io/joseederangojr/fs:${GIT_COMMIT_HASH}
    command: bun run migrate:up
    environment:
      DATABASE_URL_FILE: /run/secrets/database_url
    networks:
      - fs
    depends_on:
      - postgres
    secrets:
      - database_url
    deploy:
      restart_policy:
        condition: none

networks:
  public:
    external: true
  fs:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local

secrets:
  database_url:
    external: true
  jwt_secret:
    external: true
  postgres_password:
    external: true
